// flow-typed signature: 468f55bcfe70f4c4f93f5a9940777ae8
// flow-typed version: <<STUB>>/chartjs_v^0.3.24/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chartjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chartjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chartjs/chart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chartjs/chart.js' {
  declare module.exports: $Exports<'chartjs/chart'>;
}
