// flow-typed signature: c68e3d7855e9c07c1d4a14f844dbf18e
// flow-typed version: <<STUB>>/node-waves_v^0.7.6/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-waves'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-waves' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-waves/dist/waves' {
  declare module.exports: any;
}

declare module 'node-waves/dist/waves.min' {
  declare module.exports: any;
}

declare module 'node-waves/docs/static/jquery' {
  declare module.exports: any;
}

declare module 'node-waves/docs/static/prims' {
  declare module.exports: any;
}

declare module 'node-waves/docs/static/snarl.min' {
  declare module.exports: any;
}

declare module 'node-waves/Gruntfile' {
  declare module.exports: any;
}

declare module 'node-waves/src/js/waves' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-waves/dist/waves.js' {
  declare module.exports: $Exports<'node-waves/dist/waves'>;
}
declare module 'node-waves/dist/waves.min.js' {
  declare module.exports: $Exports<'node-waves/dist/waves.min'>;
}
declare module 'node-waves/docs/static/jquery.js' {
  declare module.exports: $Exports<'node-waves/docs/static/jquery'>;
}
declare module 'node-waves/docs/static/prims.js' {
  declare module.exports: $Exports<'node-waves/docs/static/prims'>;
}
declare module 'node-waves/docs/static/snarl.min.js' {
  declare module.exports: $Exports<'node-waves/docs/static/snarl.min'>;
}
declare module 'node-waves/Gruntfile.js' {
  declare module.exports: $Exports<'node-waves/Gruntfile'>;
}
declare module 'node-waves/src/js/waves.js' {
  declare module.exports: $Exports<'node-waves/src/js/waves'>;
}
