// flow-typed signature: 85ba614290fd71f0fd32d9adfff3eca3
// flow-typed version: <<STUB>>/perfect-scrollbar_v^1.4.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'perfect-scrollbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'perfect-scrollbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'perfect-scrollbar/dist/perfect-scrollbar.common' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/dist/perfect-scrollbar.esm' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/dist/perfect-scrollbar' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/dist/perfect-scrollbar.min' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/handlers/click-rail' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/handlers/drag-thumb' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/handlers/keyboard' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/handlers/mouse-wheel' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/handlers/touch' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/index' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/lib/class-names' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/lib/css' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/lib/dom' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/lib/event-manager' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/lib/util' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/process-scroll-diff' {
  declare module.exports: any;
}

declare module 'perfect-scrollbar/src/update-geometry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'perfect-scrollbar/dist/perfect-scrollbar.common.js' {
  declare module.exports: $Exports<'perfect-scrollbar/dist/perfect-scrollbar.common'>;
}
declare module 'perfect-scrollbar/dist/perfect-scrollbar.esm.js' {
  declare module.exports: $Exports<'perfect-scrollbar/dist/perfect-scrollbar.esm'>;
}
declare module 'perfect-scrollbar/dist/perfect-scrollbar.js' {
  declare module.exports: $Exports<'perfect-scrollbar/dist/perfect-scrollbar'>;
}
declare module 'perfect-scrollbar/dist/perfect-scrollbar.min.js' {
  declare module.exports: $Exports<'perfect-scrollbar/dist/perfect-scrollbar.min'>;
}
declare module 'perfect-scrollbar/src/handlers/click-rail.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/handlers/click-rail'>;
}
declare module 'perfect-scrollbar/src/handlers/drag-thumb.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/handlers/drag-thumb'>;
}
declare module 'perfect-scrollbar/src/handlers/keyboard.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/handlers/keyboard'>;
}
declare module 'perfect-scrollbar/src/handlers/mouse-wheel.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/handlers/mouse-wheel'>;
}
declare module 'perfect-scrollbar/src/handlers/touch.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/handlers/touch'>;
}
declare module 'perfect-scrollbar/src/index.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/index'>;
}
declare module 'perfect-scrollbar/src/lib/class-names.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/lib/class-names'>;
}
declare module 'perfect-scrollbar/src/lib/css.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/lib/css'>;
}
declare module 'perfect-scrollbar/src/lib/dom.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/lib/dom'>;
}
declare module 'perfect-scrollbar/src/lib/event-manager.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/lib/event-manager'>;
}
declare module 'perfect-scrollbar/src/lib/util.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/lib/util'>;
}
declare module 'perfect-scrollbar/src/process-scroll-diff.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/process-scroll-diff'>;
}
declare module 'perfect-scrollbar/src/update-geometry.js' {
  declare module.exports: $Exports<'perfect-scrollbar/src/update-geometry'>;
}
