// flow-typed signature: 6d4ad49851661e5a5fb6fe418515fa42
// flow-typed version: <<STUB>>/react-toast-notifications_v^1.3.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toast-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toast-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toast-notifications/dist/colors' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/icons' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/index' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/styled' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/ToastController' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/ToastElement' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/ToastProvider' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/types' {
  declare module.exports: any;
}

declare module 'react-toast-notifications/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toast-notifications/dist/colors.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/colors'>;
}
declare module 'react-toast-notifications/dist/icons.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/icons'>;
}
declare module 'react-toast-notifications/dist/index.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/index'>;
}
declare module 'react-toast-notifications/dist/styled.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/styled'>;
}
declare module 'react-toast-notifications/dist/ToastContainer.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/ToastContainer'>;
}
declare module 'react-toast-notifications/dist/ToastController.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/ToastController'>;
}
declare module 'react-toast-notifications/dist/ToastElement.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/ToastElement'>;
}
declare module 'react-toast-notifications/dist/ToastProvider.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/ToastProvider'>;
}
declare module 'react-toast-notifications/dist/types.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/types'>;
}
declare module 'react-toast-notifications/dist/utils.js' {
  declare module.exports: $Exports<'react-toast-notifications/dist/utils'>;
}
declare module 'react-toast-notifications/index' {
  declare module.exports: $Exports<'react-toast-notifications'>;
}
declare module 'react-toast-notifications/index.js' {
  declare module.exports: $Exports<'react-toast-notifications'>;
}
